import Footer from '@/components/Footer';
import Header from '@/components/Header'
import '@/styles/index.scss';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ClientLayout({ children }) {
  return (
    <>
        <Header />
        <main>
          {children}
        </main>
         <Footer />
    </>
  )
}
